In [1]:
#dependices
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('data.csv')

In [3]:
dataset.head(11)

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD  TAX  \
0   0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296   
1   0.02731   0.0   7.07     0  0.469  6.421   78.9  4.9671    2  242   
2   0.02729   0.0   7.07     0  0.469  7.185   61.1  4.9671    2  242   
3   0.03237   0.0   2.18     0  0.458  6.998   45.8  6.0622    3  222   
4   0.06905   0.0   2.18     0  0.458  7.147   54.2  6.0622    3  222   
5   0.02985   0.0   2.18     0  0.458  6.430   58.7  6.0622    3  222   
6   0.08829  12.5   7.87     0  0.524  6.012   66.6  5.5605    5  311   
7   0.14455  12.5   7.87     0  0.524  6.172   96.1  5.9505    5  311   
8   0.21124  12.5   7.87     0  0.524  5.631  100.0  6.0821    5  311   
9   0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5  311   
10  0.22489  12.5   7.87     0  0.524    NaN   94.3  6.3467    5  311   

    PTRATIO       B  LSTAT  MEDV  
0      15.3  396.90   4.98  24.0  
1      17.8  396.90   9.14  21.6  
2      17.8  392.83   4.03  34.7  
3      18.7  394.63   2.94  33.4  
4      18.7  396.90   5.33  36.2  
5      18.7  394.12   5.21  28.7  
6      15.2  395.60  12.43  22.9  
7      15.2  396.90  19.15  27.1  
8      15.2  386.63  29.93  16.5  
9      15.2  386.71  17.10  18.9  
10     15.2  392.52  20.45  15.0

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null int64
NOX        506 non-null float64
RM         501 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null int64
TAX        506 non-null int64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
MEDV       506 non-null float64
dtypes: float64(11), int64(3)
memory usage: 55.4 KB


In [5]:
dataset.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  501.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284341   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.705587   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.884000   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208000   
75%      3.677082   12.500000   18.100000    0.000000    0.624000    6.625000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [6]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [7]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [8]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [9]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='mean')
n1=imputer.fit_transform(dataset)

In [10]:
dataset1=pd.DataFrame(n1,columns=dataset.columns)

In [11]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
n2=std.fit_transform(dataset1)

In [12]:
dataset2=pd.DataFrame(n2,columns=dataset1.columns)

In [13]:
import sklearn.utils
dataset2=sklearn.utils.shuffle(dataset2)
dataset2.reset_index(drop = True)

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0   -0.369812 -0.487722 -0.079780  3.668398 -0.567496 -1.340681  1.117494   
1    0.142225 -0.487722  1.015999 -0.272599  0.244507 -0.540841 -0.546740   
2    0.340419 -0.487722  1.015999  3.668398  0.659147  1.043154  1.028593   
3   -0.401972 -0.487722 -0.616727 -0.272599 -0.921667 -0.104566 -2.207419   
4   -0.227734 -0.487722  1.231945 -0.272599  2.732346 -0.231456  1.021481   
5   -0.409341  1.229060 -0.689681 -0.272599 -0.930305  0.812184 -0.916570   
6    0.311246 -0.487722  1.015999 -0.272599  1.600725  0.080780  0.989476   
7   -0.391193 -0.487722 -0.079780 -0.272599 -0.567496 -0.714782  0.146691   
8   -0.278125 -0.487722  1.231945 -0.272599  0.434551  0.939075  1.025037   
9   -0.407685  0.585267 -0.876445 -0.272599 -0.878475  0.244740 -0.027556   
10   0.840293 -0.487722  1.015999 -0.272599  1.073787  0.709531  0.790337   
11  -0.382062 -0.487722 -0.720322 -0.272599 -0.412006 -0.282783 -0.251588   
12   1.768579 -0.487722  1.015999 -0.272599  0.365444 -2.361509  1.117494   
13  -0.327103 -0.487722 -0.437258 -0.272599 -0.144217 -1.180998 -1.137046   
14  -0.393896 -0.487722 -0.375976 -0.272599 -0.299707  0.172028  0.598310   
15  -0.416670 -0.487722 -0.867691 -0.272599 -0.342899 -0.321278 -1.112153   
16  -0.385703  0.370669 -0.609431 -0.272599 -0.783454 -0.610703 -0.941463   
17  -0.344101  0.370669 -1.045700 -0.272599  0.797361  0.795075  1.117494   
18   1.236195 -0.487722  1.015999 -0.272599  1.194724  0.083632  1.117494   
19  -0.416206  0.370669 -1.139082 -0.272599 -0.965723  0.974718 -1.115709   
20   1.345702 -0.487722  1.015999 -0.272599  1.600725 -0.188684  1.117494   
21  -0.404165 -0.487722 -0.079780 -0.272599 -0.567496  0.129256 -1.289956   
22  -0.410924  0.799865 -0.905627 -0.272599 -1.094434  0.280384 -1.780692   
23  -0.405321 -0.487722 -0.164408 -0.272599 -0.066472 -0.587891  0.160915   
24  -0.342325 -0.487722 -0.437258 -0.272599 -0.144217 -0.672009  0.772557   
25  -0.356504  0.370669 -1.045700 -0.272599  0.797361  1.314044  0.818786   
26   0.672301 -0.487722  1.015999 -0.272599  1.600725 -0.937197  0.900575   
27  -0.385816 -0.487722 -0.720322 -0.272599 -0.437921  1.998399 -1.834033   
28   2.598274 -0.487722  1.015999 -0.272599  1.073787 -1.397710  0.729884   
29   0.648606 -0.487722  1.015999 -0.272599  1.255192 -1.066939  1.117494   
..        ...       ...       ...       ...       ...       ...       ...   
476 -0.416852  3.589637 -1.410473 -0.272599 -1.310392  0.984699 -1.894486   
477  9.933931 -0.487722  1.015999 -0.272599  1.004680  0.974718  0.829454   
478  0.516961 -0.487722  1.015999 -0.272599  0.253146 -1.222344  0.953916   
479 -0.391010 -0.487722 -0.180458 -0.272599 -0.092387 -0.825989  0.324494   
480  1.658688 -0.487722  1.015999 -0.272599  1.004680 -0.087457  1.117494   
481 -0.416354  0.370669 -1.139082 -0.272599 -0.965723  2.189447 -0.144906   
482 -0.351851 -0.487722  1.568995 -0.272599  0.598679  0.124978  1.042817   
483 -0.418448  3.589637 -1.410473 -0.272599 -1.310392  1.212817 -1.944271   
484 -0.395935  0.048772 -0.476654 -0.272599 -0.265154 -0.931494  1.117494   
485  2.465737 -0.487722  1.015999 -0.272599  1.194724 -1.333552  0.975252   
486 -0.348983 -0.487722 -0.720322 -0.272599 -0.412006  0.475710  0.434732   
487 -0.305491 -0.487722 -0.437258 -0.272599 -0.144217 -0.672009  1.117494   
488 -0.409853 -0.487722 -0.047680 -0.272599 -1.224009 -0.312723 -2.161190   
489 -0.386664 -0.487722  1.568995 -0.272599  0.598679 -0.157318  0.889907   
490 -0.418179  3.589637 -1.233923 -0.272599 -1.197230  2.494555 -1.304180   
491 -0.418728  3.375039 -1.077800 -0.272599 -1.388137  1.667627 -1.222391   
492 -0.331885  0.370669 -1.045700 -0.272599  0.797361 -1.032721 -0.205359   
493 -0.264247 -0.487722  1.231945 -0.272599  0.434551 -0.311298  1.117494   
494 -0.353569 -0.487722 -0.720322 -0.272599 -0.412006  2.926554  0.168027   
495 -0.399178 -0.487722  2.422565 -0.272599  0.469104 -1.240879  1.057042   
496 -

In [14]:
dataset2.head(11)

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
209 -0.369812 -0.487722 -0.079780  3.668398 -0.567496 -1.340681  1.117494   
487  0.142225 -0.487722  1.015999 -0.272599  0.244507 -0.540841 -0.546740   
370  0.340419 -0.487722  1.015999  3.668398  0.659147  1.043154  1.028593   
43  -0.401972 -0.487722 -0.616727 -0.272599 -0.921667 -0.104566 -2.207419   
150 -0.227734 -0.487722  1.231945 -0.272599  2.732346 -0.231456  1.021481   
275 -0.409341  1.229060 -0.689681 -0.272599 -0.930305  0.812184 -0.916570   
446  0.311246 -0.487722  1.015999 -0.272599  1.600725  0.080780  0.989476   
207 -0.391193 -0.487722 -0.079780 -0.272599 -0.567496 -0.714782  0.146691   
157 -0.278125 -0.487722  1.231945 -0.272599  0.434551  0.939075  1.025037   
62  -0.407685  0.585267 -0.876445 -0.272599 -0.878475  0.244740 -0.027556   
416  0.840293 -0.487722  1.015999 -0.272599  1.073787  0.709531  0.790337   

          DIS       RAD       TAX   PTRATIO         B     LSTAT      MEDV  
209  0.038009 -0.637962 -0.779455  0.066796  0.441052  1.462985 -0.275664  
487 -0.305540  1.661245  1.530926  0.806576  0.345881 -0.168638 -0.210362  
370 -1.232462  1.661245  1.530926  0.806576  0.387875 -1.358713  2.989460  
43   0.915493 -0.752922 -1.040783 -0.256858  0.414299 -0.730735  0.235872  
150 -1.034899 -0.523001 -0.031105 -1.736418  0.176811  0.202823 -0.112408  
275  0.224497 -0.637962 -0.916058 -0.395567  0.441052 -1.355910  1.030385  
446 -0.819081  1.661245  1.530926  0.806576 -0.423926  0.720064 -0.830735  
207  0.266139 -0.637962 -0.779455  0.066796  0.359148  0.757911 -0.003571  
157 -0.911636 -0.523001 -0.031105 -1.736418  0.074075 -1.130230  2.042574  
62   1.630734 -0.178120 -0.737880  0.575395  0.441052 -0.830258 -0.036222  
416 -0.939112  1.661245  1.530926  0.806576 -3.674201  1.841454 -1.636133

In [15]:
dataset2.describe()

CRIM            ZN         INDUS          CHAS           NOX  \
count  5.060000e+02  5.060000e+02  5.060000e+02  5.060000e+02  5.060000e+02   
mean  -1.123388e-16  6.319056e-17  2.843575e-16  7.021173e-18 -2.738258e-16   
std    1.000990e+00  1.000990e+00  1.000990e+00  1.000990e+00  1.000990e+00   
min   -4.197819e-01 -4.877224e-01 -1.557842e+00 -2.725986e-01 -1.465882e+00   
25%   -4.109696e-01 -4.877224e-01 -8.676906e-01 -2.725986e-01 -9.130288e-01   
50%   -3.906665e-01 -4.877224e-01 -2.110985e-01 -2.725986e-01 -1.442174e-01   
75%    7.396560e-03  4.877224e-02  1.015999e+00 -2.725986e-01  5.986790e-01   
max    9.933931e+00  3.804234e+00  2.422565e+00  3.668398e+00  2.732346e+00   

                 RM           AGE           DIS           RAD           TAX  \
count  5.060000e+02  5.060000e+02  5.060000e+02  5.060000e+02  5.060000e+02   
mean   1.137430e-15 -1.614870e-16 -1.176047e-16  1.404235e-17  1.404235e-17   
std    1.000990e+00  1.000990e+00  1.000990e+00  1.000990e+00  1.000990e+00   
min   -3.882772e+00 -2.335437e+00 -1.267069e+00 -9.828429e-01 -1.313990e+00   
25%   -5.686434e-01 -8.374480e-01 -8.056878e-01 -6.379618e-01 -7.675760e-01   
50%   -1.059913e-01  3.173816e-01 -2.793234e-01 -5.230014e-01 -4.646726e-01   
75%    4.767793e-01  9.067981e-01  6.623709e-01  1.661245e+00  1.530926e+00   
max    3.558156e+00  1.117494e+00  3.960518e+00  1.661245e+00  1.798194e+00   

            PTRATIO             B         LSTAT          MEDV  
count  5.060000e+02  5.060000e+02  5.060000e+02  5.060000e+02  
mean  -4.124939e-16 -7.275691e-16 -3.299951e-16 -5.318539e-16  
std    1.000990e+00  1.000990e+00  1.000990e+00  1.000990e+00  
min   -2.707379e+00 -3.907193e+00 -1.531127e+00 -1.908226e+00  
25%   -4.880391e-01  2.050715e-01 -7.994200e-01 -5.994557e-01  
50%    2.748590e-01  3.811865e-01 -1.812536e-01 -1.450593e-01  
75%    8.065758e-01  4.336510e-01  6.030188e-01  2.685231e-01  
max    1.638828e+00  4.410519e-01  3.548771e+00  2.989460e+00

In [16]:
x1=dataset2.iloc[:,:-1].values
y1=dataset2.iloc[:,-1].values

In [17]:
x1

array([[-0.36981244, -0.48772236, -0.07978012, ...,  0.06679585,
         0.44105193,  1.46298491],
       [ 0.14222513, -0.48772236,  1.01599907, ...,  0.80657583,
         0.3458813 , -0.16863793],
       [ 0.34041922, -0.48772236,  1.01599907, ...,  0.80657583,
         0.38787479, -1.35871335],
       ...,
       [-0.39246798, -0.48772236, -0.54814912, ...,  0.52915834,
         0.44105193,  0.01919494],
       [ 0.1080405 , -0.48772236,  1.01599907, ...,  0.80657583,
         0.19610817, -0.68167397],
       [-0.4163466 ,  2.94584308, -1.13324559, ..., -1.08911039,
         0.44105193, -1.11901618]])

In [18]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x1,y1,test_size=0.2,random_state=0)

## Model  


## 1. Linear regression

In [19]:
from sklearn.linear_model import LinearRegression
regressor1=LinearRegression()
regressor1.fit(xtrain,ytrain)
regressor1.predict(xtest)

array([-4.36715077e-01, -4.33321844e-01,  3.41620640e-01, -8.68904788e-01,
       -3.71496169e-01, -1.78748361e-03, -9.51521956e-01, -8.85639518e-01,
        2.43009996e+00,  9.56062887e-01, -2.12605941e+00,  2.61904231e-01,
       -1.79839075e+00,  6.05157851e-01, -4.05047013e-01, -4.80967051e-02,
       -5.92286050e-01,  3.05758049e-01,  2.25022776e+00, -1.00247202e+00,
       -8.54210911e-01,  1.03267259e+00, -5.76101158e-02,  1.61327807e-01,
        5.59681576e-01, -8.09252685e-01,  3.10711731e-01, -2.93935346e-01,
       -6.49257708e-01, -1.62907374e-01, -6.61308032e-01,  1.50001599e+00,
        7.10300997e-02,  1.01412104e+00, -6.95649876e-01, -5.96713280e-01,
        6.43737895e-01, -3.24908479e-02,  4.79655184e-02, -8.73967191e-01,
        3.09544978e-01,  9.17417045e-01,  1.40074850e+00,  5.56610807e-01,
        4.69342594e-01, -8.63719537e-02, -2.92207850e-01, -8.66059704e-01,
        1.89655173e-01,  1.56859447e-02, -4.50824797e-01, -1.61072548e+00,
        1.28918301e+00, -

In [20]:
regressor1.score(xtest,ytest)

0.7878560806663647

In [21]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(regressor1,xtest,ytest,scoring="neg_mean_squared_error", cv=10)
rmse_scores = np.sqrt(-scores)

In [22]:
print(scores.std())

0.19448222107318713


## 2. Decision Tree

In [23]:
from sklearn.tree import DecisionTreeRegressor
regressor2=DecisionTreeRegressor()
regressor2.fit(xtrain,ytrain)
regressor2.predict(xtest)

array([-0.83073539, -0.68924667, -0.0362218 , -0.59129294, -0.88515413,
       -0.14505928, -0.79808414, -0.75454915,  2.1514115 ,  1.10657171,
       -0.79808414,  0.00731319, -1.66878396,  0.45354685, -0.67836292,
       -0.41715297, -1.15724782,  1.57457287,  2.98946007, -0.84161913,
       -0.9939916 ,  0.64945431, -0.55864169,  0.26852314,  0.71475679,
       -0.77631665,  0.26852314, -0.5151067 , -0.80896789, -0.55864169,
       -0.86338663,  2.42350519, -0.33008299,  0.14880191, -0.55864169,
       -0.34096674,  0.39912811, -0.35185049, -0.59129294, -0.42803672,
        0.00731319,  0.61680306,  2.82620386,  0.13791816, -0.02533805,
        0.1923369 , -0.286548  , -0.54775795,  0.17056941, -0.0579893 ,
       -0.63482793, -0.7436654 ,  0.921548  , -0.5151067 ,  0.71475679,
       -0.95045661, -0.41715297, -0.09064054, -1.07017784, -0.0362218 ,
       -0.60217668, -0.34096674,  2.98946007,  0.20322065,  0.20322065,
        2.04257402, -0.89603787, -1.25520155,  0.06173193, -0.24

In [24]:
regressor2.score(xtest,ytest)

0.7342361993607248

In [25]:
scores = cross_val_score(regressor2,xtest,ytest,scoring="neg_mean_squared_error", cv=10)
rmse_scores = np.sqrt(-scores)

In [26]:
scores.std()

0.09147367852919035

## 3. Random Forest

In [27]:
from sklearn.ensemble import RandomForestRegressor
regressor3=RandomForestRegressor()
regressor3.fit(xtrain,ytrain)
regressor3.predict(xtest)

c:\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


array([-0.89712625, -0.07540329,  0.15859728, -0.89386112, -0.66421405,
       -0.11240804, -0.81223302, -0.77196315,  2.52907754,  1.1631672 ,
       -0.64353493,  0.02908069, -1.80591919,  0.62551006, -1.19316419,
       -0.20056639, -1.02555447,  1.05215297,  2.37235158, -0.8775355 ,
       -1.05602897,  0.57979832, -0.32899462,  0.25110914,  0.55367733,
       -0.72951653,  0.18254153, -0.23865951, -0.59999993, -0.24954326,
       -0.9939916 ,  2.34949571, -0.19185939,  0.99446911, -0.57061382,
       -0.40409247,  0.61244957, -0.12002666, -0.12329178, -0.40844597,
       -0.10478941,  0.90304563,  2.16882549,  0.39586298,  0.07914593,
       -0.10261266, -0.19294777, -0.27675263,  0.13791816,  0.08567617,
       -0.68489317, -0.70883741,  1.29159542, -0.70557229,  0.9520225 ,
       -0.92651237, -0.23104089, -0.27566425, -0.82747026,  0.12703442,
       -0.57387894, -0.34314349, -0.34640861, -0.19185939,  0.0889413 ,
        1.70844296, -0.72189791, -1.09629883,  0.42416073, -0.20

In [28]:
regressor3.score(xtest,ytest)

0.9077438288914619

In [29]:
scores = cross_val_score(regressor3,xtest,ytest,scoring="neg_mean_squared_error", cv=10)
rmse_scores = np.sqrt(-scores)

In [30]:
scores.std()

0.0878647699584704